"""
Модуль с правильными примерами данных, получаемых от сервера.
"""

class CorrectResponses():
    """
    Класс переменных, хранящих правильные ответы от сервера.
    """
    stats_data_for_info_type_3 = {'Alek Mist': 43, 'AnDes': 1, 'AndatraLesnaya': 6,
                                   'Andever': 375, 'Anticvariat': 36, 'Aquaman': 2, 'Aritan': 3,
                                   'Arkrade': 1, 'Artemides': 3, 'Arthur': 8, 'Azrael': 27,
                                   'BadDancer': 1, 'Barry Allen': 1, 'BarsETKA': 243,
                                   'Bat-bat': 126, 'Batgirl': 3, 'Batman Beyond2011': 48,
                                   'Bats': 5, 'Bayern': 1, 'Bazinga': 4, 'Beavart': 2,
                                   'BlackJack_in_Box': 1, 'Blackroom': 2, 'Blue beetle': 2,
                                   'Boga1': 1, 'ChaosGypsy': 1, 'Comik26': 3, 'CronosOne': 1,
                                   'Crystallin': 15, 'Danil': 1, 'Dark Lanter': 1, 'Darkness': 2,
                                   'Darth Revan': 58, 'Deathstroke': 6, 'Demonsochi13': 1,
                                   'Denispak777': 2, 'Depressa': 73, 'Detective': 40,
                                   'DiamonD': 8, 'Dizzy Rockin': 14, 'Dragon': 14, 'Drinkins': 36,
                                   'Durer': 5, 'EliZiuM': 2, 'Exc1t3r': 2, 'Fakety': 1,
                                   'Femis': 11, 'Fenaris': 4, 'Finegan': 14, 'FlaimZ': 2,
                                   'G21K': 1, 'GOUST': 52, 'GRPF_1': 9, 'GoshaDude89': 1,
                                   'Gratar': 2, 'Gregory': 20, 'Grengo': 1, 'GreyFox': 2,
                                   'GrinDoS': 2, 'Guybrush': 1, 'HaVoK': 10, 'Hal': 4,
                                   'Hallas': 5, 'Happy rasta': 3, 'Hellspawn': 47, 'Hush': 6,
                                   'ILDAR-J': 3, 'Imp': 25, 'J-Doe': 3, 'J.J.Jox': 3, 'JPage': 6,
                                   'Jamce': 18, 'Jedispb': 1, 'Jesterrus': 1, 'Jetpack': 2,
                                   'John Axel Shepard': 4, 'Joker Earth-Two': 100,
                                   'Jokester': 102, 'Joseph Curwen': 4, 'Joyst': 7,
                                   'KAPTOIIIKA': 1, 'KOStEt_58': 2, 'Kal-Ust': 7, 'KazikZ': 9,
                                   'Kendrol': 3, 'Kirtie': 3, 'Komrad_Toky': 2, 'Koyoth': 7,
                                   'KujinofuWarado': 1, 'Lacrimosa': 10, 'LexVort': 33,
                                   'Liberalnaya_N': 4, 'Little Bastard': 9, 'Lonsd8': 1,
                                   'Louman': 1, 'MadMind': 3, 'Mahun': 1, 'Mamoru': 5,
                                   'Man of Steel ': 127, 'MarchCat': 4, 'Martin Winters': 2,
                                   'Mattias1994': 2, 'Maxno': 39, 'McPixel': 2, 'Medved': 1,
                                   'Mega amper': 4, 'MegaTumoxa': 4, 'Mell': 3, 'Miles': 2,
                                   'Monarch': 1, 'Moonknight': 2, 'NeitralWitch': 1,
                                   'New_Enigma': 6, 'Nik562': 1, 'Nixtwelve': 2, 'Nuez': 1,
                                   'Nurken4ik': 9, 'Nyan': 2, 'P-E-R-S-T': 2, 'Pa_Ko': 2,
                                   'Piro': 98, 'PrAl': 195, 'RadRigerss': 2, 'RangerKnight': 20,
                                   'Ratel': 1, 'Repter': 4, 'Riccio': 2, 'Rio': 13, 'Rokuss': 1,
                                   'Romazeo': 22, 'Ross': 1, 'RussianFireball': 2, 'SabZero': 1,
                                   'Sakket': 4, 'Savvon': 4, 'Schoss': 3, 'Serheus': 3,
                                   'Shadow500': 17, 'Shalqer': 1, 'Shaqler': 1, 'Shazaaam': 2,
                                   'Shuher': 31, 'Sicilian': 115, 'Sinestro': 5,
                                   'Skwigy_StarDust': 7, 'Slim': 8, 'Sly': 5, 'Sobek': 8,
                                   'Specter': 2, 'Spiritoz': 4, 'Starktron': 1, 'Stranger9475': 3,
                                   'Suicide': 3, 'Sylar': 2, 'Sylar666': 3, 'Symarip': 14,
                                   'Taron8117': 3, 'Teisson': 19, 'The Dark Joker': 6,
                                   'The Dark Knight': 2, 'The Darth Knight': 40, 'TheSnach': 1,
                                   'The_GraF': 1, 'Thomas_Yorke': 6, 'Todd': 95, 'Tsuomi': 56,
                                   'Two-Face': 36, 'Tаylor Gang': 5, 'Ugly': 11, 'Unicorn': 1,
                                   'Vandal Savage': 187, 'Vasil': 82, 'VirgilMount': 4,
                                   'Virus': 1, 'Vynder': 1, 'Wally_West': 7, 'Wassup': 42,
                                   'Wayne39': 2, 'YO-YO': 3, 'ZOKiCH': 2, 'ZXC.IgUANA': 4,
                                   'ZhirAKLE': 1, 'ZoKpooL': 3, 'abask': 1, 'alex 52': 16,
                                   'alexey_ko': 4, 'algait767': 9, 'alive': 12, 'ar75': 2,
                                   'bat4653': 14, 'bats_bats': 3, 'blue_beetle': 64, 'buddy': 3,
                                   'dagon1210': 3, 'danildaken': 308, 'dantes': 1, 'dontknow': 3,
                                   'doom': 3, 'dr.Tolstiy': 3, 'eXIIImeKCC': 2, 'farmboy': 22,
                                   'ferfromdno': 1, 'focirr': 1, 'forgery': 62, 'gantz ICHIGO': 1,
                                   'good day': 17, 'greven': 47, 'gushindaniil': 1,
                                   'happyrasta': 10, 'iSnuppI': 1, 'knoppix': 1, 'kurare': 91,
                                   'mechanic': 2, 'mikess': 1, 'mjc01': 2, 'mrazovic': 2,
                                   'nechiporukoleg': 75, 'nicoist': 1, 'nvdse': 2, 'omega': 1,
                                   'petway': 10, 'red_robin': 29, 'robottx': 1, 'sam_nesung': 1,
                                   'sat7': 2, 'set-night': 7, 'shaman7207': 3, 'slipbullet': 3,
                                   'soer inc': 4, 'superurman': 21, 'thefur': 16, 'topwriter': 2,
                                   'troll': 1, 'uazzo': 2, 'vest82': 2, 'witold': 2, 'zhedon': 6,
                                   'zombinatrbol': 2, 'Александэр': 2, 'Бабур': 14, 'Бэтс': 239,
                                   'Гайвер III': 1, 'Генерал': 69, 'Грек': 1, 'Гудвин': 54,
                                   'Джоель-Кент': 73, 'Иван Добронравов': 4, 'Катка': 6,
                                   'Койот': 1, 'Колючий': 3, 'Косяшек': 18, 'Крест': 7,
                                   'Крис': 217, 'Лапы Ярости': 1, 'Люцифер333': 3, 'МаксиBat': 8,
                                   'Роршах': 4, 'Сигма': 1, 'Сицилиец': 22, 'Супербой-16': 2,
                                   'Супербэт': 1, 'Супергерой': 1, 'Тэпп': 9, 'Ужас и Страх': 1,
                                   'сетхе': 1, 'усатый_кавказэц': 1}

    stats_data_for_info_type_4 = {'Alek Mist': 9975, 'AnDes': 160, 'AndatraLesnaya': 1100,
                                  'Andever': 86587, 'Anticvariat': 3872, 'Aquaman': 387,
                                  'Aritan': 365, 'Arkrade': 198, 'Artemides': 1390, 'Arthur': 819,
                                  'Azrael': 1929, 'BadDancer': 122, 'Barry Allen': 27,
                                  'BarsETKA': 18328, 'Bat-bat': 15635, 'Batgirl': 65,
                                  'Batman Beyond2011': 3570, 'Bats': 122, 'Bayern': 106,
                                  'Bazinga': 375, 'Beavart': 81, 'BlackJack_in_Box': 134,
                                  'Blackroom': 284, 'Blue beetle': 346, 'Boga1': 1,
                                  'ChaosGypsy': 232, 'Comik26': 769, 'CronosOne': 140,
                                  'Crystallin': 1928, 'Danil': 204, 'Dark Lanter': 27,
                                  'Darkness': 71, 'Darth Revan': 5394, 'Deathstroke': 460,
                                  'Demonsochi13': 107, 'Denispak777': 128, 'Depressa': 5396,
                                  'Detective': 2648, 'DiamonD': 545, 'Dizzy Rockin': 1728,
                                  'Dragon': 1076, 'Drinkins': 6341, 'Durer': 2734, 'EliZiuM': 101,
                                  'Exc1t3r': 230, 'Fakety': 140, 'Femis': 951, 'Fenaris': 190,
                                  'Finegan': 2980, 'FlaimZ': 228, 'G21K': 146, 'GOUST': 6713,
                                  'GRPF_1': 795, 'GoshaDude89': 284, 'Gratar': 70,
                                  'Gregory': 1630, 'Grengo': 83, 'GreyFox': 386, 'GrinDoS': 302,
                                  'Guybrush': 61, 'HaVoK': 453, 'Hal': 419, 'Hallas': 836,
                                  'Happy rasta': 654, 'Hellspawn': 3345, 'Hush': 515,
                                  'ILDAR-J': 492, 'Imp': 2049, 'J-Doe': 453, 'J.J.Jox': 634,
                                  'JPage': 232, 'Jamce': 1085, 'Jedispb': 80, 'Jesterrus': 116,
                                  'Jetpack': 318, 'John Axel Shepard': 772,
                                  'Joker Earth-Two': 11302, 'Jokester': 36224,
                                  'Joseph Curwen': 885, 'Joyst': 1377, 'KAPTOIIIKA': 152,
                                  'KOStEt_58': 225, 'Kal-Ust': 800, 'KazikZ': 1267,
                                  'Kendrol': 125, 'Kirtie': 127, 'Komrad_Toky': 192,
                                  'Koyoth': 323, 'KujinofuWarado': 32, 'Lacrimosa': 932,
                                  'LexVort': 3982, 'Liberalnaya_N': 687, 'Little Bastard': 748,
                                  'Lonsd8': 234, 'Louman': 535, 'MadMind': 421, 'Mahun': 229,
                                  'Mamoru': 763, 'Man of Steel ': 21240, 'MarchCat': 592,
                                  'Martin Winters': 335, 'Mattias1994': 52, 'Maxno': 4810,
                                  'McPixel': 244, 'Medved': 31, 'Mega amper': 420,
                                  'MegaTumoxa': 1991, 'Mell': 123, 'Miles': 590, 'Monarch': 91,
                                  'Moonknight': 221, 'NeitralWitch': 259, 'New_Enigma': 1112,
                                  'Nik562': 50, 'Nixtwelve': 49, 'Nuez': 124, 'Nurken4ik': 575,
                                  'Nyan': 97, 'P-E-R-S-T': 153, 'Pa_Ko': 204, 'Piro': 8058,
                                  'PrAl': 19918, 'RadRigerss': 290, 'RangerKnight': 828,
                                  'Ratel': 40, 'Repter': 639, 'Riccio': 46, 'Rio': 1608,
                                  'Rokuss': 23, 'Romazeo': 4011, 'Ross': 198,
                                  'RussianFireball': 161, 'SabZero': 284, 'Sakket': 555,
                                  'Savvon': 176, 'Schoss': 458, 'Serheus': 80, 'Shadow500': 1995,
                                  'Shalqer': 152, 'Shaqler': 274, 'Shazaaam': 278, 'Shuher': 1475,
                                  'Sicilian': 24361, 'Sinestro': 576, 'Skwigy_StarDust': 302,
                                  'Slim': 223, 'Sly': 846, 'Sobek': 1357, 'Specter': 45,
                                  'Spiritoz': 159, 'Starktron': 35, 'Stranger9475': 406,
                                  'Suicide': 208, 'Sylar': 142, 'Sylar666': 213, 'Symarip': 1075,
                                  'Taron8117': 263, 'Teisson': 4481, 'The Dark Joker': 1164,
                                  'The Dark Knight': 385, 'The Darth Knight': 24026,
                                  'TheSnach': 179, 'The_GraF': 44, 'Thomas_Yorke': 1028,
                                  'Todd': 11741, 'Tsuomi': 8356, 'Two-Face': 2835,
                                  'Tаylor Gang': 1156, 'Ugly': 1110, 'Unicorn': 125,
                                  'Vandal Savage': 28820, 'Vasil': 8541, 'VirgilMount': 122,
                                  'Virus': 93, 'Vynder': 167, 'Wally_West': 297, 'Wassup': 3168,
                                  'Wayne39': 595, 'YO-YO': 372, 'ZOKiCH': 171, 'ZXC.IgUANA': 157,
                                  'ZhirAKLE': 32, 'ZoKpooL': 174, 'abask': 145, 'alex 52': 1650,
                                  'alexey_ko': 1205, 'algait767': 1267, 'alive': 953, 'ar75': 125,
                                  'bat4653': 7680, 'bats_bats': 235, 'blue_beetle': 17476,
                                  'buddy': 155, 'dagon1210': 242, 'danildaken': 24630,
                                  'dantes': 52, 'dontknow': 957, 'doom': 182, 'dr.Tolstiy': 190,
                                  'eXIIImeKCC': 278, 'farmboy': 2554, 'ferfromdno': 255,
                                  'focirr': 44, 'forgery': 5408, 'gantz ICHIGO': 16,
                                  'good day': 4528, 'greven': 3311, 'gushindaniil': 375,
                                  'happyrasta': 917, 'iSnuppI': 249, 'knoppix': 352,
                                  'kurare': 27947, 'mechanic': 129, 'mikess': 221, 'mjc01': 237,
                                  'mrazovic': 98, 'nechiporukoleg': 8385, 'nicoist': 128,
                                  'nvdse': 608, 'omega': 725, 'petway': 994, 'red_robin': 2240,
                                  'robottx': 76, 'sam_nesung': 27, 'sat7': 71, 'set-night': 1334,
                                  'shaman7207': 755, 'slipbullet': 351, 'soer inc': 817,
                                  'superurman': 3007, 'thefur': 3439, 'topwriter': 205,
                                  'troll': 281, 'uazzo': 170, 'vest82': 147, 'witold': 428,
                                  'zhedon': 320, 'zombinatrbol': 74, 'Александэр': 667,
                                  'Бабур': 1808, 'Бэтс': 76511, 'Гайвер III': 146,
                                  'Генерал': 12432, 'Грек': 49, 'Гудвин': 11455,
                                  'Джоель-Кент': 11667, 'Иван Добронравов': 736, 'Катка': 286,
                                  'Койот': 63, 'Колючий': 214, 'Косяшек': 1542, 'Крест': 1279,
                                  'Крис': 25083, 'Лапы Ярости': 420, 'Люцифер333': 956,
                                  'МаксиBat': 608, 'Роршах': 196, 'Сигма': 482, 'Сицилиец': 1767,
                                  'Супербой-16': 174, 'Супербэт': 224, 'Супергерой': 20,
                                  'Тэпп': 600, 'Ужас и Страх': 80, 'сетхе': 141,
                                  'усатый_кавказэц': 94}

    users_list = ['Бэтс', 'Гудвин', 'Durer', 'Anticvariat', 'YO-YO', 'danildaken',
                  'nechiporukoleg', 'thefur', 'kurare', 'BarsETKA', 'Jokester', 'greven',
                  'Bazinga', 'PrAl', 'Depressa', 'farmboy', 'Джоель-Кент', 'Vandal Savage',
                  'alex 52', 'Taron8117', 'Jamce', 'Тэпп', 'Kirtie', 'Крис', 'GOUST',
                  'Demonsochi13', 'HaVoK', 'Vasil', 'forgery', 'buddy', 'iSnuppI', 'Andever',
                  'Hellspawn', 'MarchCat', 'GreyFox', 'Maxno', 'KazikZ', 'The Darth Knight',
                  'Man of Steel ', 'Генерал', 'MegaTumoxa', 'Kal-Ust', 'Louman', 'Bat-bat',
                  'Sylar666', 'Drinkins', 'alive', 'blue_beetle', 'Arkrade', 'NeitralWitch',
                  'Gregory', 'superurman', 'Dizzy Rockin', 'ChaosGypsy', 'Unicorn', 'Femis',
                  'Wassup', 'Comik26', 'Sly', 'Bats', 'Symarip', 'Crystallin', 'Joseph Curwen',
                  'EliZiuM', 'Alek Mist', 'Shadow500', 'Лапы Ярости', 'FlaimZ', 'GrinDoS',
                  'red_robin', 'dontknow', 'uazzo', 'Barry Allen', 'bat4653', 'Detective', 'Imp',
                  'KujinofuWarado', 'RangerKnight', 'Shuher', 'troll', 'Aritan', 'Sobek',
                  'Joker Earth-Two', 'doom', 'New_Enigma', 'ZOKiCH', 'Azrael', 'Martin Winters',
                  'Little Bastard', 'Sicilian', 'Moonknight', 'LexVort', 'Beavart', 'Romazeo',
                  'Teisson', 'Slim', 'Todd', 'Nurken4ik', 'Jetpack', 'Piro', 'Катка', 'Бабур',
                  'topwriter', 'Darth Revan', 'ZoKpooL', 'Serheus', 'усатый_кавказэц', 'Tsuomi',
                  'Nuez', 'dagon1210', 'Two-Face', 'Сицилиец', 'Gratar', 'МаксиBat', 'ar75',
                  'algait767', 'Сигма', 'set-night', 'Koyoth', 'vest82', 'Супербой-16',
                  'ferfromdno', 'DiamonD', 'Skwigy_StarDust', 'Крест', 'Deathstroke', 'Wayne39',
                  'Ratel', 'Thomas_Yorke', 'shaman7207', 'Pa_Ko', 'JPage', 'zombinatrbol',
                  'The Dark Joker', 'сетхе', 'Shazaaam', 'Spiritoz', 'Lacrimosa', 'Косяшек',
                  'Hallas', 'sat7', 'RussianFireball', 'Artemides', 'gantz ICHIGO', 'Fenaris',
                  'Nik562', 'Batgirl', 'BadDancer', 'Койот', 'Batman Beyond2011', 'Shalqer',
                  'Грек', 'G21K', 'GoshaDude89', 'TheSnach', 'Fakety', 'witold', 'Mega amper',
                  'ZXC.IgUANA', 'petway', 'Suicide', 'Wally_West', 'GRPF_1', 'Shaqler',
                  'Tаylor Gang', 'Mamoru', 'Guybrush', 'Danil', 'Роршах', 'Hal', 'abask',
                  'RadRigerss', 'Dragon', 'P-E-R-S-T', 'The_GraF', 'Mattias1994', 'eXIIImeKCC',
                  'Александэр', 'Stranger9475', 'good day', 'alexey_ko', 'ZhirAKLE', 'Exc1t3r',
                  'Kendrol', 'Joyst', 'Starktron', 'Колючий', 'Riccio', 'focirr', 'Medved',
                  'gushindaniil', 'Specter', 'ILDAR-J', 'Finegan', 'Mell', 'mikess',
                  'Иван Добронравов', 'AndatraLesnaya', 'mrazovic', 'bats_bats', 'nicoist',
                  'Blue beetle', 'Savvon', 'zhedon', 'Ужас и Страх', 'Komrad_Toky', 'J-Doe',
                  'Darkness', 'mechanic', 'SabZero', 'Nyan', 'Sinestro', 'Grengo', 'Dark Lanter',
                  'Arthur', 'Sylar', 'Sakket', 'dantes', 'McPixel', 'robottx', 'Happy rasta',
                  'Nixtwelve', 'Rio', 'Jedispb', 'Liberalnaya_N', 'Aquaman', 'CronosOne',
                  'The Dark Knight', 'Schoss', 'Virus', 'Lonsd8', 'happyrasta', 'AnDes',
                  'VirgilMount', 'John Axel Shepard', 'Супергерой', 'BlackJack_in_Box', 'Rokuss',
                  'Miles', 'J.J.Jox', 'Hush', 'dr.Tolstiy', 'KOStEt_58', 'KAPTOIIIKA',
                  'slipbullet', 'Blackroom', 'soer inc', 'Vynder', 'Ugly', 'MadMind',
                  'Гайвер III', 'sam_nesung', 'Супербэт', 'mjc01', 'Jesterrus', 'knoppix',
                  'omega', 'Monarch', 'Repter', 'nvdse', 'Denispak777', 'Mahun', 'Boga1', 'Ross',
                  'Bayern', 'Люцифер333']
